# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zoe and Carl's Wedding!
home_title: Save the date!
#email: carl@shapiro.cc
description: Zoe Hendrickson and Carl Shapiro's wedding website
url: "http://www.bmorezarl.com"
github_username: crshapiro/BmoreZarl

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true